### ISSUE TITLE
Menu doesn't open on Firefox

### ISSUE THREAD

**Issue by fbnlsr** [impshum/Tutor-Piles#1]
When moving the mouse to the left, the menu doesn't open. Works fine on Chrome.

MacOS v10.14.2
Firefox v64.0

**Comment by impshum** [comment]
Exactly the same setup here and it works for me but for some reason moving the mouse to the far left really quickly doesn't trigger it. I'll look into this.

**Comment by fbnlsr** [comment]
You might want to add a couple keyboard shortcuts as well for "home" or to quickly switch between slideshows, or maybe a blindfold.

**Comment by impshum** [comment]
That's not a bad idea.
